### ISSUE TITLE
can search in archive

### ISSUE THREAD

**Issue by SimplyY** [fniephaus/alfred-pocket#15]
I can't find how to search item in archive.

please help.

**Comment by fniephaus** [comment]
Currently, the workflow ignores archived items, so there is no way to list them or search through them.
How often do you look at archived items?

**Comment by SimplyY** [comment]
I want to use it to search what I have read.

Beacause some items is very useful, such as code articles.

**Comment by fniephaus** [comment]
It's possible, but you would need to change the code.
I can't test anything right now, but basically you need to edit this file:
https://github.com/fniephaus/alfred-pocket/blob/master/src/pocket_refresh.py

**[L20](https://github.com/fniephaus/alfred-pocket/blob/master/src/pocket_refresh.py#L20)**
```state = None``` change to ```state = 'all'```

**[L75-L77](https://github.com/fniephaus/alfred-pocket/blob/master/src/pocket_refresh.py#L75-L77)**
Comment the lines out.

That should be it.

**Comment by SimplyY** [comment]
I try it. But it don't work.

file that I changed :

![image](https://cloud.githubusercontent.com/assets/8455579/9850970/e1b63f18-5b28-11e5-8e15-315acd5dd24a.png)

**Comment by fniephaus** [comment]
Like I said, I currently don't have my MacBook, but let me get back to you in two
weeks, ok?

**Comment by SimplyY** [comment]
ok， very thanks。

**Comment by fniephaus** [comment]
Have you also tried to run `pocket wf:delcache` in Alfred to delete the cache?

**Comment by SimplyY** [comment]
![image](https://cloud.githubusercontent.com/assets/8455579/10272934/7c7c9af6-6b5a-11e5-8029-fdf10c9a7e2a.png)

I see it, and press enter. But it just seem cant be press enter...

**Comment by fniephaus** [comment]
The cache is already cleared when you see this message.
I assume this didn't solve your problem?

**Comment by SimplyY** [comment]
yes

**Comment by djan92** [comment]
Any more thoughts on how we can search through archive also? I followed the steps and no luck. Thanks so much in advance.

**Comment by fniephaus** [comment]
Hi,
I haven't forgotten about this.
Unfortunately, my MacBook is still in repair. I will follow up as soon as I can.

**Comment by djan92** [comment]
Thanks for the super quick response. Spent some time trying to debug it and it looks like the problem is somewhere in the Alfred display portion. The cached data seems to store data with time_read and grabbing archived articles.

I can't figure out why it's filtering out on the search/display.

Let me know if I can help in any way. Thanks again!

**Comment by jasontate** [comment]
This seems like a great addition, I'd like this as well.

**Comment by fniephaus** [comment]
What would be better: another script filter (e.g. `pocket-archive`) for archived items only or would it be better to do something similar to Google/Gmail search, e.g. `pocket is:archived`, or should there be a menu like `unread`, `archived`, `labeled`...what would be best?

**Comment by fniephaus** [comment]
I have just added a pre-release of v6.0 which adds support for categories:
https://github.com/fniephaus/alfred-pocket/releases/tag/v6.0
