### ISSUE TITLE
Temporarily Did Not Work

### ISSUE THREAD

**Issue by r3volution11** [fniephaus/alfred-pocket#16]
Hey, love this workflow. This isn't so much an issue as it is a question/notification.

For some reason it temporarily decided not to work. I deauthorized it and then it magically started to work again without reauthorizing. Is this something that may happen every now and then? If so it may be good to write a note in the README letting users know what to do in the event it happens.

Thanks!

**Comment by fniephaus** [comment]
Hi @r3volution11,
This is the first time that I hear about a problem like this.
Is there any way to reproduce this?

**Comment by r3volution11** [comment]
@fniephaus I haven't figured out a way to reproduce it, no.
