### ISSUE TITLE
%0A is appended to non-article URLS

### ISSUE THREAD

**Issue by nikitavoloboev** [fniephaus/alfred-pocket#19]
I have the issue with %0A being appended to a lot of my links, it seems the ones that cannot be open in 'article view' will get this %0A appended to their links thus I can't open them in browser and it is very annoying.

What can I change to remove this behaviour and have the original links being added so I can then open them in browser.

Thank you for a great workflow.

**Comment by fniephaus** [comment]
Hi @nikitavoloboev,
Thanks for opening this issue.
Is `%0A` added to the links when you add them, so that you cannot open them in Pocket's website either or is it just this workflow that can't open these kind of links?

**Comment by fniephaus** [comment]
AFAIK `%0A` is a line feed character which is interesting :)

**Comment by nikitavoloboev** [comment]
here is a screencast of the bug in action : http://quick.as/OWz4hDbWX

**Comment by fniephaus** [comment]
Thanks! I can reproduce it, that's perfect!

**Comment by fniephaus** [comment]
I've just release [v5.2](https://github.com/fniephaus/alfred-pocket/releases/tag/v5.2) which should fix this problem 😃 .

**Comment by nikitavoloboev** [comment]
that was fast, thank you
