### ISSUE TITLE
I would really love a feature where I can add an article and archive it instantly with some tag

### ISSUE THREAD

**Issue by nikitavoloboev** [fniephaus/alfred-pocket#20]
I add articles I want to read later to pocket but sometimes I come across certain articles that I read fully right from the browser, I want to have pocket be my go-to place for articles both archived and ones I want to read. Having this additional feature would allow me to just press a hotkey and archive the read article instantly in pocket with some custom tag.

Right now to achieve this behaviour, I would have to add the article to pocket, then go to pocket, find the article and archive it from there as well as add a tag for it. I want to bypass all these steps and add an article instantly.

I hope this would be possible to do. I really think it would be a great addition.

**Comment by fniephaus** [comment]
Hi @nikitavoloboev,
Thanks for the feature request. I will look into this as soon as I can.

**Comment by fniephaus** [comment]
Hi @nikitavoloboev,
How about we add a special tag called `#archive` and if you add this as a custom tag, the entry will be archived right after it has been added.
Searching through archived items is in the making (see #15)...

**Comment by nikitavoloboev** [comment]
For me it would be better to have a separate hotkey trigger that puts the article that I am viewing into archive and gives me a prompt as to what tag I want to have attached to it. 

My current use case of your workflow is simply pressing the hotkey to instantly add the article to pocket for later viewing without adding a tag. 
 
![2016-05-30 at 21 11](https://cloud.githubusercontent.com/assets/6391776/15656811/15ca903a-26ab-11e6-80e3-ce0f89aefeb3.png)

However for archiving something, I would actually like to have alfred prompt show up with what tag I want as I now have read the article and can appropriately give it the tags I want.

Thank you for adding these features, it would really be incredible to have this full workflow in place and would make managing and finding articles really great.

**Comment by fniephaus** [comment]
So you just want to be able to label links *after* you have archived them with this workflow?

**Comment by nikitavoloboev** [comment]
It would work the same as it does now, that is you trigger the hotkey, a prompt shows up and you write your tags. However instead of adding it to the pocket list, it would add it to archive.

**Comment by fniephaus** [comment]
ok, got it :)

**Comment by fniephaus** [comment]
I have just added a pre-release of v6.0 which adds a shortcut for your use-case:
https://github.com/fniephaus/alfred-pocket/releases/tag/v6.0

Please note that it requires Alfred 3.

**Comment by nikitavoloboev** [comment]
Thank you so much. ♥

I especially love the addition of choosing what exactly do you want to search in Pocket. This is awesome.

**Comment by fniephaus** [comment]
I'm glad you like it!

**Comment by nikitavoloboev** [comment]
This addition makes me think. Would it be also possible to add search by tag to that general search window?

**Comment by fniephaus** [comment]
Yep, it's possible. Please open a new issue and I will look into this as soon as I can
