### ISSUE TITLE
Can't get Pocket reading list

### ISSUE THREAD

**Issue by iyee** [fniephaus/alfred-pocket#21]
<img width="612" alt="screen shot 2016-05-27 at 17 36 58" src="https://cloud.githubusercontent.com/assets/88564/15604209/b2e8b256-2431-11e6-8a8a-bac9dcffe92f.png">
I wonder how to reauthorize to get it back to work.

**Comment by fniephaus** [comment]
`pocket wf:deauth` should do the trick :)

**Comment by iyee** [comment]
@fniephaus token delete,
<img width="619" alt="screen shot 2016-05-27 at 18 15 33" src="https://cloud.githubusercontent.com/assets/88564/15605209/1d6afb84-2437-11e6-96a6-dcaef8a89c9e.png">

The auth process completed successfully, but still can't get list in the next attempt.

**Comment by fniephaus** [comment]
Are you using the latest version?
Has it worked before?

**Comment by nikitavoloboev** [comment]
Had this happen before to me too. Adding a new article to the list fixed the issue for me.

**Comment by iyee** [comment]
@fniephaus I'm using the latest version & it was working last week. Tried reinstalling it but still fails.
@nikitavoloboev I add items everyday.

**Comment by fniephaus** [comment]
So your problem is fixed, @iyee?
How many items do you have in your account? Is there any way you can reproduce the issue?

**Comment by iyee** [comment]
@fniephaus around 300 items, & it fails again, Alfred debug info:
```
Starting debug for 'Pocket for Alfred'

[2016-05-30 10:26:07][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Your Pocket list is empty!</title><subtitle /><icon>icons/info-dark.png</icon></item></items>
```
Nothing can be traced...

**Comment by fniephaus** [comment]
What happens after you cleared the cache (`pocket wf:delcache`)?

**Comment by iyee** [comment]
It's still returning empty list:
```
[2016-05-30 15:57:17][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Deleted workflow cache</title><subtitle /><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ToolbarInfo.icns</icon></item></items>
[2016-05-30 15:57:32][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Your Pocket list is empty!</title><subtitle /><icon>icons/info-dark.png</icon></item></items>
```

**Comment by fniephaus** [comment]
Would you mind sending me your token to [the email address on my profile](https://github.com/fniephaus/).
You can find it in your Keychain by searching for `com.fniephaus.pocket`.

**Comment by iyee** [comment]
@fniephaus Sent, thanks for helping.

**Comment by iyee** [comment]
the workflow returns results from time to time, but mixed with some outdated items.

**Comment by fniephaus** [comment]
I received your token, but everything seems to be working on my system.
What OS X version are you using?

**Comment by iyee** [comment]
@fniephaus I guess the server is not stable enough to offer data all the time, it's working for me now.

OS X 10.11.5

**Comment by fniephaus** [comment]
Mh, interesting. I haven't really noticed any problems like this myself, but it seems that there is a problem with Pocket's API when it's been used by multiple clients for the same user. BTW: their last update for the API docs page is from 2012 😢

**Comment by fniephaus** [comment]
I've updated the way entries are synced once more. I hope it's more stable with the next release...
