### ISSUE TITLE
[feature request] add possibility to favourite archived article with modifier keypress

### ISSUE THREAD

**Issue by nikitavoloboev** [fniephaus/alfred-pocket#25]
Recently you have added a great addition of archiving articles instantly and giving the article a set of tags. It would be really nice if one could additionally have the ability to press modifier key command or other modifier to also favourite that entry. 

I hope it won't be too difficult to implement and you can agree on its usefulness. Thank you so much for such a great workflow.

**Comment by fniephaus** [comment]
This should be fairly simple, but I don't want to overload the workflow with too many features that only few users have. I'll integrate this as soon as I have some time...

**Comment by nikitavoloboev** [comment]
Hey, 

Just wanted to bump this issue because I would really love to have it working. I am currently somewhat avoiding it by using 'fav' tag but I would much rather favourite the articles the way they are supposed to be starred.

Thank you again for the workflow. :)

**Comment by fniephaus** [comment]
Hi @nikitavoloboev, sorry I'm currently very busy with other things, but it's still on my todo. I hope I'll find some time in the next two weeks. Hope that's ok...

**Comment by nikitavoloboev** [comment]
Yes, I understand. Of course.

**Comment by fniephaus** [comment]
![image](https://cloud.githubusercontent.com/assets/2368856/18275583/f5edb34c-7447-11e6-9413-320789115e31.png)
I've added a script that you can connect the `pocket` script filter with. There aren't any modifier keys left, so you'd need to replace one of them with your new favorite modifier. I'm afraid you need to customize this every time you update the workflow, but this is as best as I can get it at the moment.

**Comment by nikitavoloboev** [comment]
Hey Fabio,

I just tried to use this but it seems to not work for some reason. I made a screencast of me trying to use it here : http://quick.as/5O34f1XDA

Perhaps I am using it wrong or doing something wrong.

Thank you for any help. Love the workflow.

**Comment by fniephaus** [comment]
Are you sure you pressed `ctrl` when hitting enter? Did the link end up in your favorite list instead?

**Comment by nikitavoloboev** [comment]
I m sure. It didn't end up in neither.

**Comment by fniephaus** [comment]
You need to connect the favorite "Run Script" with the "Main script filter" and then remap one of the modifier to the favorite action. Here's an example:
![image](https://cloud.githubusercontent.com/assets/2368856/19640277/3fa47052-99dc-11e6-8768-212608559109.png)
There still is a little bug that I'm going to fix now, but then you can use the modifier in the pocket list to favorite an item.

**Comment by fniephaus** [comment]
here you go: https://github.com/fniephaus/alfred-pocket/releases/tag/v6.2

**Comment by nikitavoloboev** [comment]
But it should archive the article, with tags I wrote and favourite it if pressed with a modifier key. Do I understand that correct?

**Comment by fniephaus** [comment]
No, that's not how the favorite option works. You can only favorite a link from the list of links you see in Alfred and that you already have in your Pocket list. You can't add a new link to your Pocket list, archive, and favorite it in one step.

**Comment by nikitavoloboev** [comment]
Oh I understand that now. My bad. For me though it would be much more intuitive to both archive a link with tags and favourite it instantly all in one step as when I have read the link, I know if it will be a favourite.

**Comment by fniephaus** [comment]
Could you open a new feature request/issue for that? I'm currently very busy with other things. If you have some time, maybe try implementing this yourself and contribute your changes. I'm happy to assist :)
