### ISSUE TITLE
Tags starting with a dot '.' are not accepted

### ISSUE THREAD

**Issue by Meflou** [fniephaus/alfred-pocket#27]

**Comment by fniephaus** [comment]
![image](https://cloud.githubusercontent.com/assets/2368856/18273602/5f22ac0a-743e-11e6-90e7-688e64c2fd11.png)
Hi @Meflou, I can't seem to reproduce your problem. Do you have a problem adding links with tags starting with a dot or searching for links with such tags?

**Comment by fniephaus** [comment]
Tag handling has changed in v6.1, please reopen if it still doesn't work.
