### ISSUE TITLE
[feature request] favourite and archive a link with tags with one hotkey

### ISSUE THREAD

**Issue by nikitavoloboev** [fniephaus/alfred-pocket#29]

**Comment by nikitavoloboev** [comment]
I will try to implement it myself and hopefully succeed. :)

**Comment by fniephaus** [comment]
Let me know if you need any help. Basically you need to add the link to Pocket first and then archive and favorite it instantly afterwards.

**Comment by nikitavoloboev** [comment]
I no longer use Pocket so this issue can be closed. I doubt anyone else wants this feature.
