### ISSUE TITLE
bug with update in new alfred version

### ISSUE THREAD

**Issue by nikitavoloboev** [fniephaus/alfred-pocket#30]
![2016-10-26 at 01 57](https://cloud.githubusercontent.com/assets/6391776/19708544/912765bc-9b1f-11e6-9d62-99deb162e177.png)

This message shows up every time. It is unclickable and I believe I am on the latest version. (one from Packal).

**Comment by fniephaus** [comment]
Forgot to bump the version file. Resolved in [`v6.3`](https://github.com/fniephaus/alfred-pocket/releases/tag/v6.3).
