### ISSUE TITLE
Adding a link from Chrome doesn't work if Chrome is not installed in `/Applications`

### ISSUE THREAD

**Issue by danielma** [fniephaus/alfred-pocket#34]
I've installed Chrome using `brew cask`, so it's installed at `/usr/local/Caskroom/google-chrome/latest`. 

[`pocket_save.py`](https://github.com/fniephaus/alfred-pocket/blob/master/src/pocket_save.py#L62) assumes that Chrome will always be installed at `/Applications/Chrome.app`.

In order to save links to pocket, I have to copy the link from Chrome, then focus on a different app and use the `add-pocket` workflow to use the contents of the clipboard

**Comment by fniephaus** [comment]
Thanks for opening the issue.
Is there a good way to identify Chrome's installation path other than trying out different default directories? Does it work when you change the path to `/usr/local/Caskroom/google-chrome/latest` in your `pocket_save.py`?

**Comment by danielma** [comment]
I tried it out locally, and everything worked properly when I identified Chrome only by the app name and not by the path. I've submitted a PR for that change
