### ISSUE TITLE
Your pocket list is empty! But it's not

### ISSUE THREAD

**Issue by godbout** [fniephaus/alfred-pocket#37]
Hi there,

Installed the workflow and authorized it, but it tells me my lists are empty. They are not. Here's the debug info:

Any help?

```
[2017-04-17 20:20:45][STDERR: input.scriptfilter] 20:20:45 workflow.py:2153 DEBUG    Workflow version : 6.5.0
20:20:45 workflow.py:1554 DEBUG    Reading settings from `/Users/guill/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.pocket/settings.json` ...
20:20:45 workflow.py:2437 DEBUG    Update check not due
20:20:45 workflow.py:2317 DEBUG    Last run version : 6.5.0
20:20:45 workflow.py:2317 DEBUG    Last run version : 6.5.0
20:20:45 workflow.py:1789 DEBUG    Loading cached data from : /Users/guill/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.pocket/__workflow_update_status.cpickle
20:20:45 workflow.py:2365 DEBUG    update_data : {u'available': False}
20:20:45 workflow.py:2557 DEBUG    Got password : com.fniephaus.pocket:pocket_access_token
20:20:45 workflow.py:2557 DEBUG    Got password : com.fniephaus.pocket:pocket_access_token
20:20:45 workflow.py:2347 DEBUG    Set last run version : 6.5.0
20:20:45 workflow.py:2191 DEBUG    Workflow finished in 0.158 seconds.
[2017-04-17 20:20:54][STDERR: input.scriptfilter] 20:20:48 workflow.py:2153 DEBUG    Workflow version : 6.5.0
20:20:48 workflow.py:1554 DEBUG    Reading settings from `/Users/guill/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.pocket/settings.json` ...
20:20:48 workflow.py:2437 DEBUG    Update check not due
20:20:48 workflow.py:2317 DEBUG    Last run version : 6.5.0
20:20:48 workflow.py:2317 DEBUG    Last run version : 6.5.0
20:20:48 workflow.py:1789 DEBUG    Loading cached data from : /Users/guill/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.pocket/__workflow_update_status.cpickle
20:20:48 workflow.py:2365 DEBUG    update_data : {u'available': False}
20:20:48 workflow.py:2557 DEBUG    Got password : com.fniephaus.pocket:pocket_access_token
20:20:48 workflow.py:2557 DEBUG    Got password : com.fniephaus.pocket:pocket_access_token
20:20:54 workflow.py:2347 DEBUG    Set last run version : 6.5.0
20:20:54 workflow.py:2191 DEBUG    Workflow finished in 5.691 seconds.

**Comment by fniephaus** [comment]
What Alfred version are you using? I've just updated to the latest version and also have the problem now...

**Comment by fniephaus** [comment]
Okay, there was a `Python` process running at 100% in my Activity Monitor. After killing it, the list appeared again...could you check if this is also your problem?

**Comment by godbout** [comment]
Hey Fabio. Yes, same issue. Python process eating the CPU. It seems to be a problem with macOS Sierra. I've updated the alfred-workflow python framework that you are using, and it works now every time. You might want to update that in your own workflow and release a new version? Cheers.

**Comment by godbout** [comment]
(Oh btw if you don't mind me asking here, are you able to upload your workflow on packal? I've been trying to push new ones for a few months now, the site always crashes.)

**Comment by fniephaus** [comment]
Hi @godbout, thanks for confirming. I've already updated `alfred-workflow` in the meantime. I'm glad @deanishe stays on top of things. Also, I was able to update the `alfred-pocket` workflow on packal, not sure what happens when I try to add a new one. Maybe ping @shawnrice?

**Comment by godbout** [comment]
Excellent, thanks.
I've contacted a few times @shawnrice about that but no answer.

**Comment by deanishe** [comment]
It might be worth [running this workflow](https://github.com/deanishe/alfred-fixum).

It'll fix any other workflows you have that are using buggy version of Alfred-Workflow until developers push official updates.

Regarding Packal: sometimes it works, sometimes it doesn't. Shawn's too busy to work on it atm.

**Comment by godbout** [comment]
Alright, thanks @deanishe for confirming about Packal.
Workflow works great, 3 were out of date!
