### ISSUE TITLE
Python running for extensive times

### ISSUE THREAD

**Issue by jasontate** [fniephaus/alfred-pocket#38]
I'm seeing Python running in the background, pretty extensively, due to this Workflow. Has anyone else seen this? 

<img width="351" alt="screen shot 2017-04-26 at 12 35 43 pm" src="https://cloud.githubusercontent.com/assets/7143532/25453171/e6c6c3cc-2a7c-11e7-9712-01604814b06c.png">

**Comment by fniephaus** [comment]
Is your problem related to https://github.com/deanishe/alfred-workflow/issues/111?

**Comment by wcsherrod** [comment]
I've noticed the same problem occurring intermittently. It does not seem to be related to the issue described in the thread above. I'm running Alfred 3.3.2 on 10.12.6 beta. The problem started within the past month or so, possibly after a system update.

<img width="557" alt="screen shot 2017-06-21 at 7 16 27 am" src="https://user-images.githubusercontent.com/13273984/27383864-6b7a697e-5652-11e7-8cf1-b0e533aca222.png">

**Comment by deanishe** [comment]
@wcsherrod: Try running [this workflow](https://github.com/deanishe/alfred-fixum). It should fix the issue with Python workflows hanging and consuming 100% of CPU.

**Comment by fniephaus** [comment]
@deanishe Looks like it...will fix that soon, thanks!

**Comment by fniephaus** [comment]
Should be fixed in [`v6.7`](https://github.com/fniephaus/alfred-pocket/releases/tag/v6.7).
