### ISSUE TITLE
Use url as uid to make alfred sort result automatically.

### ISSUE THREAD

**Issue by SFurnace** [fniephaus/alfred-pocket#39]
I think add this feature will make this great workflow even more useful.

Just add `uid=link['given_url'],` in pocket.py:167 is enough.

**Comment by fniephaus** [comment]
Feel free to open a PR for this, so it will count as your contribution ;)

**Comment by SFurnace** [comment]
OK, thanks~

**Comment by fniephaus** [comment]
Closing this in favor of #40
