### ISSUE TITLE
Open Search in Pocket?

### ISSUE THREAD

**Issue by proxemics** [fniephaus/alfred-pocket#44]
Absolutely love this workflow! I use Pocket extensively and it works flawlessly, really great stuff!

Was curious, is it possible to open a search in Pocket web? I know I can open the link in Pocket using shift, curious if this kind of functionality can be added to an entire search?

The search is amazing in this workflow, but sometimes it's easier for me to find the article using the images and visual layout in Pocket. Just a thought.

Thanks for the great tool!!

**Comment by fniephaus** [comment]
Thanks, @proxemics! Glad you like it.
I don't think Pocket's API provides any search hooks and [their website](https://getpocket.com/a/queue/list/) does not seem to accept any parameters, so I'm afraid your request is not possible at the moment.
Feel free to re-open this if you come across a way to programmatically open their search page.

**Comment by proxemics** [comment]
Ah, gotcha. Thanks for the quick response and for even considering it! 🙏
