### ISSUE TITLE
[Suggestion] Add the action to select a random article

### ISSUE THREAD

**Issue by Kitefr** [fniephaus/alfred-pocket#45]
Hello !

Just started using your workflow and it is amazing.
I'd like to add  a feature to it. 

The action "random" will call the url : `https://getpocket.com/random` which randomly select an article from your list you haven't read yet.

I can add it myself with the Alfred workflow system but it will by nice to have it in yours.

Thank you !

**Comment by fniephaus** [comment]
A `Random` action should be easy to implement. However, I would be against calling the `/random` URL, because it requires to be logged in in your browser. Instead, why not randomly select a URL locally instead?
Pull requests are more than welcome, otherwise I'm not sure how soon I have time to work on this.

**Comment by Kitefr** [comment]
In that case, we can retrieve a list of random articles instead of just one. I'll check that this weekend.

**Comment by fniephaus** [comment]
Yes, that should also be no problem...just randomly sort the list of all items. The workflow downloads all items anyway...

**Comment by Kitefr** [comment]
I was thinking about doing it this way : 
`pocket rand` and `pocket random` will be valid options.
`pocket random 6` limit to 6 the number of articles. Limited to 10 by default.

I do not want to change the flow of your script. What do you think about it ?
Or do you prefer `pocket in:random` to just mimic the other categories ?

**Comment by fniephaus** [comment]
Hi @Kitefr,
I don't think you need to limit the number of articles by default though.
Also, I think it'd make sense to mimic other categories, just add a new item in the overview? I just checked and `pocket random` actually matches a few articles in my list. I wouldn't want to change the default search behavior if that makes sense.

**Comment by Kitefr** [comment]
Hi, 
I made the change locally, it works great. I didn't cached the data so every input change the result. I do not think it was necessary for a random function.
I already choose `pocket in:random` but i am wondering if `as:random` would be better as random is not an actual category inside pocket.

I choose to limit the result to 10 articles as people would mostly as a few random articles to read directly instead of going through all the list if they do not want them. The point is for them to read those articles. I am thinking of limiting the result to `unread` article as well. What is your opinion ?

**Comment by fniephaus** [comment]
`as:random` makes sense. No need to cache random data at this point as all articles are already cached and it should be relatively cheap to just randomize them.

What do you mean by *limiting the result to `unread` articles*? Which `unread` articles?

**Comment by Kitefr** [comment]
Unread articles are the one with status `unread` from the API. 
Those are articles which are not in the archive category. What the point of getting articles as random if you already read them.

**Comment by fniephaus** [comment]
Ah okay, so you want a *random unread articles* category?

**Comment by Kitefr** [comment]
I found it more normal this way, don't you think so too ?

**Comment by fniephaus** [comment]
If you're adding a new category, that's fine and you can just randomly show unread items. I just want to make sure the current behavior is not changed :)

**Comment by Kitefr** [comment]
For now, i added a new category: `random`.
As a category, i need to use `in` instead of `as`, otherwise i will have to change a lot of things and i do not want to.
I use your current script behavior as much as i can.

**Comment by fniephaus** [comment]
Thanks, feel free to open a PR when you are ready and I'll have a look.

**Comment by Kitefr** [comment]
Just done so. Feel free to look at is when you like.

**Comment by fniephaus** [comment]
Thanks, closing this in favor of #46.
