### ISSUE TITLE
Refresh when Link is deleted

### ISSUE THREAD

**Issue by spearkkk** [fniephaus/alfred-pocket#54]
Hi, Iam spearkkk

Thank you for your nice sharing.
Would you update this workflows?
If link is removed in my pocket, the list will be refreched automatically.

Thanks!

**Comment by fniephaus** [comment]
Hi @spearkkk,
I'm not sure I understand your request: do you want the workflow to reopen itself after you have deleted an entry? Or is the list not being updated on your machine?

**Comment by spearkkk** [comment]
FIrst of all, The deletion flow is following:
1. I open workflow and move into my Pocket list.
2. I select a element of list to delete.
3. I delele the element using `cmd` + `enter`.
4. There is a notification(pop-up) for notifying the deletion.
5. But there is still the element in the list(NOT auto refresh).
6. I close the workflow, and re-open it(or go back and move into Pocket list again).
7. I check whether it is deleted or not.

I just want to know whether my action is done or not.
So Could you add auto-refresh when I deletem some element of list?

'do you want the workflow to reopen itself after you have deleted an entry'
This is my request for this workflow.

I always thank you and your nice sharing.

---
Hi @spearkkk,
I'm not sure I understand your request: do you want the workflow to reopen itself after you have deleted an entry? Or is the list not being updated on your machine?
