### ISSUE TITLE
Alfred 3 compatibility of v7.3

### ISSUE THREAD

**Issue by pqrth** [fniephaus/alfred-pocket#55]
First of all @fniephaus, thanks a ton for creating and maintaining this powerful workflow for my beloved reading list service 😍

Now, I installed _alfred-pocket_ v7.3 from both [Packal](https://www.packal.org/workflow/pocket-alfred) and [GitHub releases page](https://github.com/fniephaus/alfred-pocket/releases/tag/v7.3) with SHA-256 _324ec3030a92f04e3ac3017ebf867f1634aa15c2c316ca44356ad889869b4d4d_, but it shows following error:
> Workflow Incompatible. Please update to the latest version of Alfred

<img width="365" alt="image" src="https://user-images.githubusercontent.com/6792160/78718030-28a4a200-793f-11ea-8d35-a83f8e41fcdc.png">

Now, v7.2 is compatible with Alfred 3, so I checked [the diff from v7.2 and v7.3](https://github.com/fniephaus/alfred-pocket/compare/v7.2...v7.3), but I couldn't identify what's breaking the compatibility.

@fniephaus, could you please help me understand why v7.3 doesn't support Alfred 3, because a simple web search didn't help?

**Comment by fniephaus** [comment]
AFAIK nothing that changed from 7.2 to 7.3 should cause this behavior. I'm guessing Alfred 3 has noticed that this is a workflow for a newer version of Alfred. Considering Alfred 4 was released almost a year ago, I probably don't want to maintain compatibility if it's too much effort. Why are you still on 3 anyway? Any particular reason?

**Comment by fniephaus** [comment]
Closing this for now, the workflow is currently only supported on the latest Alfred release (v4 at the moment).
