### ISSUE TITLE
Reset authentication

### ISSUE THREAD

**Issue by arliber** [fniephaus/alfred-pocket#57]
Hello,

First of all, thanks for making this, it's amazing!

I would love to know how can I reset the credentials to my Pocket account as I have 2 accounts and authenticated with the wrong one by mistake.

Deleting the folder `/Users/***/Library/Caches/com.runningwithcrayons.Alfred/` didn't help - I can still it successfully logging `got password : com.fniephaus.pocket:pocket_access_token` and getting into the incorrect account.

Thanks,
Arik

**Comment by fniephaus** [comment]
Hi @arliber,
You can remove your token using Apple's "Keychain Access". Just search for "com.fniephaus.pocket", delete the entry, and try again.

Cheers,
Fabio
