### ISSUE TITLE
In the request pocket, can add a proxy configuration？

### ISSUE THREAD

**Issue by philipbo** [fniephaus/alfred-pocket#58]
### Motivation

In China, because of the network problem, accessing the pocket is very slow

thanks!

**Comment by fniephaus** [comment]
Hi @philipbo,

This workflow uses [`urllib2`](https://docs.python.org/2/library/urllib2.html) and you can [configure an http proxy with environment variables](https://stackoverflow.com/a/3168244).

Please feel free to re-open this issue if you have any further questions!
