### ISSUE TITLE
Feature: Open in Pocket

### ISSUE THREAD

**Issue by macx** [fniephaus/alfred-pocket#6]
I miss the option “Open in Pocket“ instead of open the source url in the browser. By this way I'm able to view the article in the readability mode. Any plans?

**Comment by fniephaus** [comment]
Hi @macx,
That shouldn't be much of a problem and I'm happy to add this.
Just to make sure: are you talking about the pocket website or about a native client?

**Comment by macx** [comment]
For the beginning I think the website is enough. If it isn't a deal you can think about open it in the chrome app or in the native app, if it support direct links. For me, chrome is ok.

Pressing the return key should open it in Pocket (browser). We already heave with CTRL the option to open it in the browser (and to archive it).

BTW: Great extension!

**Comment by fniephaus** [comment]
Thanks. I'll have a look into that as soon as I can.

**Comment by fniephaus** [comment]
I had some time to work on this. It's now possible to register custom magic arguments with `Alfred-Workflow`, so I have moved the deauthorization functionality to `wf:deauth`.

The shift action can now be used to open links as suggested on getpocket.com.
Here's the commit: f3a14fc1f4cd9378b61f9678aa14a5aba2ef887c

I will keep working on the workflow in the next couple of days.
The new features will be available as soon as I push the next update.
