### ISSUE TITLE
Pocket List ist Empty!

### ISSUE THREAD

**Issue by ired** [fniephaus/alfred-pocket#8]
Thank you for the workflow! It has worked for me until today. It tells me that my pocket list were empty, which is not.

this is the debug info alfred shows:

Starting debug for 'Pocket for Alfred'

[STDERR: alfred.workflow.input.scriptfilter] 13:05:02 workflow.py:1610 DEBUG    Loading cached data from : /Users/vladislavgapurov/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.pocket/__workflow_update_status.cpickle
13:05:02 workflow.py:2181 DEBUG    update_data : {u'available': False, u'version': u'4.1', u'download_url': u'https://github.com/fniephaus/alfred-pocket/releases/download/v4.1/Pocket-for-Alfred.alfredworkflow'}
13:05:02 workflow.py:2350 DEBUG    Got password : com.fniephaus.pocket:pocket_access_token
13:05:02 workflow.py:2350 DEBUG    Got password : com.fniephaus.pocket:pocket_access_token
13:05:02 background.py:188 DEBUG    Command arguments cached to `/Users/vladislavgapurov/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.pocket/pocket_refresh.argcache`
13:05:02 background.py:192 DEBUG    Calling [u'/usr/bin/python', '/Users/vladislavgapurov/Dropbox/alfredapp/Alfred.alfredpreferences/workflows/user.workflow.E93CE79B-A70B-4175-9CDC-6CA2F1F92C5F/workflow/background.pyc', 'pocket_refresh'] ...
13:05:02 workflow.py:1972 DEBUG    Workflow version : 4.1.0
13:05:02 workflow.py:2008 DEBUG    Workflow finished in 0.037 seconds.
13:05:02 workflow.py:2008 DEBUG    Workflow finished in 0.039 seconds.
13:05:02 background.py:197 DEBUG    Executing task `pocket_refresh` in background...
13:05:03 workflow.py:1610 DEBUG    Loading cached data from : /Users/vladislavgapurov/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.pocket/pocket_list.cpickle
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Your Pocket list is empty!</title><subtitle /></item></items>

**Comment by fniephaus** [comment]
Hi @ired,
Thanks for your bug report.
Could please try again with the latest version of the workflow:
https://github.com/fniephaus/alfred-pocket/releases/tag/v4.2

You might also want to try and run `pocket wf:reset` to reset the workflow.

**Comment by ired** [comment]
thanks! it has worked even without reseting.

**Comment by fniephaus** [comment]
That's great. Thanks for getting in touch.
